package constants

const (
	CONST_SEAT_STOREFRONT_SLOT_CODE_SEAT     = "SEAT"
	CONST_SEAT_STOREFRONT_SLOT_CODE_AISLE    = "AISLE"
	CONST_SEAT_STOREFRONT_SLOT_CODE_BLANK    = "BLANK"
	CONST_SEAT_STOREFRONT_SLOT_CODE_BULKHEAD = "BULKHEAD"
)
